New text for about page
rtcharity/eahub.org pull request #1197
Opened 2021-03-08 16:07 UTC by jnsya

2021-03-09 08:49 UTC, sebgrebe commented
The real names issue is a good question, actually. Initially, I thought we would want to put real names, but one might argue that someone could contribute under their github alias, without having to reveal their identity. That's how open source projects work.
So I think I'm changing my mind and would prefer github usernames.

Also, please add "Anastasiia Kuvshinova". She contributed code, but it got lost on github. I don't have her github account name. @victor-yunenko, do you have it? And are you OK with using github usernames?

2021-03-09 08:52 UTC, sebgrebe requested changes
Minor: Please convert png to jpg, as jpg is smaller in size.
@vagarwalla could you have a final look please whether you're happy with the text?

2021-03-09 08:57 UTC, sebgrebe requested changes

2021-03-09 08:57 UTC, sebgrebe commented on eahub/templates/eahub/about.html
> +        <p>If you are an EA-aligned organisation and believe you could benefit from our data, please <a href="mailto:vaidehi@eahub.org"> contact Vaidehi, our Product Manager</a>.</p>
I'd only put the link on "Vaidehi"

2021-03-09 08:57 UTC, sebgrebe commented on eahub/templates/eahub/about.html
> +          <li><a href="https://github.com/sebgrebe">sebgrebe</a></li>
please put in alphabetical order

2021-03-09 08:57 UTC, sebgrebe commented on eahub/templates/eahub/about.html
> +        <p>The EA Hub was originally created by Tom Ash in 2014 to host both his own projects (beginning with the <a href="https://www.rethinkprojects.org/easurvey">EA Survey</a> and the public <a hr
Put "Rethink Charity" in quotes in "Renamed Rethink Charity"

2021-03-14 10:11 UTC, sebgrebe commented
@jnsya, discussed the name issue with @victor-yunenko. We agreed on using clear names where we have them and the github usernames where not

2021-03-14 10:12 UTC, victor-yunenko commented on eahub/templates/eahub/about.html
> +          <li><a href="https://github.com/cafelow">cafelow</a></li>
could help with adding `rel=nofollow` for SEO purposes?

2021-03-14 10:12 UTC, victor-yunenko commented
And the developer who has been helping with the frontend - Anastasiia Kuvshinova

2021-03-14 10:13 UTC, victor-yunenko commented on eahub/templates/eahub/about.html
> +        <p>We are always <a href="http://bit.ly/eahub-openroles">looking for volunteers</a> to help build the Hub, in both technical and non-technical roles. If you’re interested in tech roles, pleas
And well rel=nofollow everywhere else :)

Probably expect the forum and rethink charity, as they don't add it for our links

2021-03-21 14:40 UTC, sebgrebe commented
Closing this in lieu of [this PR](https://github.com/rtcharity/eahub.org/pull/1218) as Vaidehi asked to release ASAP and there were some changes that need to be made prior to release.

2021-03-21 14:40 UTC, closed without merging

2021-03-21 22:55 UTC, vagarwalla commented
FWIW
- Text was looking good
- I'll let the tech team decide whether you want real names or not. I think EA folks may want real names? Perhaps you can send a messaging letting them know about the About page, but and if they'd prefer github username to do that.