sso with google
rtcharity/eahub.org pull request #1239
Opened 2021-04-06 21:55 UTC by victor-yunenko

Hi @sebgrebe, it's a small addition, could you approve it for a go-live?

- https://eahub-sso-fc0721a.us.aldryn.io/
- https://eahub-sso-fc0721a.us.aldryn.io/accounts/login/
- https://eahub-sso-fc0721a.us.aldryn.io/accounts/signup/

I didn't handle the styles in a great way, but still I advise to test it like that before we do the forum post.

Related to #1170

2021-04-06 22:04 UTC, victor-yunenko commented
hm, ok there's an issue for existing users, the flow doesn't look good

2021-04-06 22:15 UTC, victor-yunenko commented
Fixed now.

2021-04-07 11:15 UTC, victor-yunenko commented
@sebgrebe, I would say the sooner we review & deploy it - the faster we can import the data safely without worrying that there's a hidden issue with the SSO that we didn't know about ;)

2021-04-07 11:16 UTC, victor-yunenko commented
Also I expect it to be the most popular option after the forum post.

2021-04-08 19:57 UTC, sebgrebe requested changes
When trying to login or signup with my Gmail account, I'm not receiving the verification email. I assume that's because we're not using the right EMAIL_URL in the environment variable of the SSO server. How did you check on your end that it worked? Locally?

2021-04-08 19:57 UTC, sebgrebe commented on eahub/templates/account/login.html
> +          <span>Sign In with Google</span>
Minor: Not sure what's common, but is it right to use the same phrase "Sign in" both for signing up and logging in?

2021-04-08 20:50 UTC, sebgrebe commented
> When trying to login or signup with my Gmail account, I'm not receiving the verification email. I assume that's because we're not using the right EMAIL_URL in the environment variable of the SSO server. How did you check on your end that it worked? Locally?

This was caused by me having had an account with an unverified email address on that server under my gmail address. Once I deleted that account, it went smoothly.

Do we have a weird edge case here where someone signs up with their email, doesn't verify the email address and then tries to login with a google account with the same email address? Shouldn't it ignore that you haven't verified your email initially in this case as a Google email is verified by definition?

2021-04-09 11:30 UTC, victor-yunenko commented
> Do we have a weird edge case here where someone signs up with their email, doesn't verify the email address and then tries to login with a google account with the same email address? Shouldn't it ignore that you haven't verified your email initially in this case as a Google email is verified by definition?

We should, but since django-allauth was enabled with multi-emails it creates complications. I thought about cutting it out several months ago, but back then I didn't have a good reason except for the potential issues.

For now I propose to leave it in place. Yes, the stage doesn't have a real email SMTP, which should be the case. It should have mailtrap on it though in the future.

Otherwise yes, you would have received a confirmation email.

2021-04-09 12:18 UTC, sebgrebe approved these changes

2021-04-09 12:20 UTC, sebgrebe commented
> We should, but since django-allauth was enabled with multi-emails it creates complications. I thought about cutting it out several months ago, but back then I didn't have a good reason except for the potential issues.

> For now I propose to leave it in place.   

Sounds good, the number of affected users will be very small (if any). I've approved. 

Can we add a ticket for fixing it so that we don't forget?

2021-04-09 12:27 UTC, victor-yunenko commented
Sure, but do you want to fix it though? They will receive the confirmation email. In the future I would prefer to prioritize cutting out the multi-email feature, since I don't think we need it?

2021-04-09 12:27 UTC, merged